# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_task_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('position',)},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('position',)},
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
